import calculate from './phases/calculations.js'

const objects = {
    inputs: [],
    phases: [
        {
            number: 1,
            name: '1',
            function: calculate,
            textOnProcessing: 1,
            textOnCompletion: 1,
            async: false,
            svgTransitionElementId: undefined,
            svgShowOnTransitionId: 'phase_1'
        },
        {
            number: 2,
            name: '2',
            function: calculate,
            textOnProcessing: 2,
            textOnCompletion: 2,
            async: false,
            svgTransitionElementId: undefined,
            svgShowOnTransitionId: 'phase_2'
        },
        {
            number: 3,
            name: '3',
            function: calculate,
            textOnProcessing: 3,
            textOnCompletion: 3,
            async: false,
            svgTransitionElementId: undefined,
            svgShowOnTransitionId: 'phase_3'
        },
        {
            number: 4,
            name: '4',
            function: calculate,
            textOnProcessing: 4,
            textOnCompletion: 4,
            async: false,
            svgTransitionElementId: undefined,
            svgShowOnTransitionId: 'phase_4'
        },
        {
            number: 5,
            name: '5',
            function: calculate,
            textOnProcessing: 5,
            textOnCompletion: 5,
            async: false,
            svgShowOnTransitionId: 'phase_5',
        },
        {
            number: 6,
            name: '6',
            function: calculate,
            textOnProcessing: 6,
            textOnCompletion: 6,
            async: false,
            svgShowOnTransitionId: 'phase_6',
        },
        {
            number: 7,
            name: '7',
            function: calculate,
            textOnProcessing: 7,
            textOnCompletion: 7,
            async: false,
            svgShowOnTransitionId: 'phase_7',
        },
        {
            number: 8,
            name: '8',
            function: calculate,
            textOnProcessing: 8,
            textOnCompletion: 8,
            async: false,
            svgShowOnTransitionId: 'phase_8',
        },
        {
            number: 9,
            name: '9',
            function: calculate,
            textOnProcessing: 9,
            textOnCompletion: 9,
            async: false,
            svgShowOnTransitionId: 'phase_9',
        },
        {
            number: 10,
            name: '10',
            function: calculate,
            textOnProcessing: 10,
            textOnCompletion: 10,
            async: false,
            svgShowOnTransitionId: 'phase_10',
        },
        {
            number: 11,
            name: '11',
            function: calculate,
            textOnProcessing: 11,
            textOnCompletion: 11,
            async: false,
            svgShowOnTransitionId: 'phase_11',
        },
        {
            number: 12,
            name: '12',
            function: calculate,
            textOnProcessing: 12,
            textOnCompletion: 12,
            async: false,
            svgShowOnTransitionId: 'phase_12',
        },
        {
            number: 13,
            name: '13',
            function: calculate,
            textOnProcessing: 13,
            textOnCompletion: 13,
            async: false,
            svgShowOnTransitionId: 'phase_13',
        },
        {
            number: 14,
            name: '14',
            function: calculate,
            textOnProcessing: 14,
            textOnCompletion: 14,
            async: false,
            svgShowOnTransitionId: 'phase_14',
        },
        {
            number: 15,
            name: '15',
            function: calculate,
            textOnProcessing: 15,
            textOnCompletion: 15,
            async: false,
            svgShowOnTransitionId: 'phase_15',
        },
        {
            number: 16,
            name: '16',
            function: calculate,
            textOnProcessing: 16,
            textOnCompletion: 16,
            async: false,
            svgShowOnTransitionId: 'phase_16',
        },
        {
            number: 17,
            name: '17',
            function: calculate,
            textOnProcessing: 17,
            textOnCompletion: 17,
            async: false,
            svgShowOnTransitionId: 'phase_17',
        },
        {
            number: 18,
            name: '18',
            function: calculate,
            textOnProcessing: 18,
            textOnCompletion: 18,
            async: false,
            svgShowOnTransitionId: 'phase_18',
        },
        {
            number: 19,
            name: '19',
            function: calculate,
            textOnProcessing: 19,
            textOnCompletion: 19,
            async: false,
            svgShowOnTransitionId: 'phase_19',
        },
        {
            number: 20,
            name: '20',
            function: calculate,
            textOnProcessing: 20,
            textOnCompletion: 20,
            async: false,
            svgShowOnTransitionId: 'phase_20',
        },
        {
            number: 21,
            name: '21',
            function: calculate,
            textOnProcessing: 21,
            textOnCompletion: 21,
            async: false,
            svgShowOnTransitionId: 'phase_21',
        },
        {
            number: 22,
            name: '22',
            function: calculate,
            textOnProcessing: 22,
            textOnCompletion: 22,
            async: false,
            svgShowOnTransitionId: 'phase_22',
        },
        {
            number: 23,
            name: '23',
            function: calculate,
            textOnProcessing: 23,
            textOnCompletion: 23,
            async: false,
            svgShowOnTransitionId: 'phase_23',
        },
        {
            number: 24,
            name: '24',
            function: calculate,
            textOnProcessing: 24,
            textOnCompletion: 24,
            async: false,
            svgShowOnTransitionId: 'phase_24',
        },
        {
            number: 25,
            name: '25',
            function: calculate,
            textOnProcessing: 25,
            textOnCompletion: 25,
            async: false,
            svgShowOnTransitionId: 'phase_25',
        },



    ],
    periods: [1]
}

export default objects;